
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest


steps:
- script: |
    chmod a=rwx,o+t /tmp  
    cd src/
    make init
    make
    make run RUNSCRIPT=unit_schedtests.sh run
  displayName: 'Trying to build system'
