- name: Azure Pipelines Action
  uses: Azure/pipelines@v1

trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest

steps:
- script: |
    cd src
    make init
    make
  displayName: 'Build system'
- script: |
    ls
    cd src
    timeout --preserve-status 10 make run RUNSCRIPT=unit_schedtests.sh run
    exit 0
  displayName: 'Run Qemu'


