
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest


steps:
- script: |
    cd src
    make init
    make
  displayName: 'Build system'
- script: |
    cd src
    make run RUNSCRIPT=unit_schedtests.sh run > output.txt
  timeoutInMinutes: 1
  displayName: 'Run Qemu'
- script: |
    cd src
    cat output.txt
  displayName: 'Showing Test Results'



