trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest

steps:
- script: |
    cd src
    make init
    make
  displayName: 'Build system'
- script: |
    ls
    cd src
    timeout --preserve-status 10 make run RUNSCRIPT=kernel_tests.sh run > ../kernel_tests.txt
    exit 0
  displayName: 'Run Qemu Kernel Tests'
- script: |
    cat kernel_tests.txt
  displayName: 'Display Kernel Tests'
  
- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      with open('kernel_tests.txt') as f:
        if 'Kernel boot complete' in f.read():
          print("Kernel Boot Complete")
          exit(0)
      print("Kernel Boot not Complete")
      exit(1)
  displayName: 'Check Kernel Boot'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      with open('kernel_tests.txt') as f:
        if '(0,1,0) 	One-Shot Timeout: 			Success' in f.read():
          print("One-Shot Timeout Success")
          exit(0)
      print("One-Shot Timeout Failure")
      exit(1)
  displayName: 'Check One-Shot Timeout'


