
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest

steps:
- script: |
    cd src
    make init
    make
  displayName: 'Build system'
- script: |
    ls
    cd src
    timeout 10 --preserve-status make run RUNSCRIPT=unit_schedtests.sh run
  displayName: 'Run Qemu'


