
trigger:
- master

steps:
- task: Docker@2
  inputs:
    repository: 'grahamschock/composite_dev_env'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- script: |
    cd src/
    make init
    make
    make run RUNSCRIPT=kernel_tests.sh run
  displayName: 'Trying to build system'
