
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest


steps:
- script: |
    chmod o+rwx /tmp
    cd src
    make init
    make
    cd ../transfer
    sh unit_schedtests.sh
  displayName: 'Trying to build system'
