trigger:
- '*'

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest

steps:
- script: |
    cd src
    make init
    make
  displayName: 'Build system'
- script: |
    ls
    cd src
    timeout --preserve-status 10 make run RUNSCRIPT=kernel_tests.sh run > ../kernel_tests.txt
    exit 0
  displayName: 'Run Qemu Kernel Tests'
- script: |
    cat kernel_tests.txt
  displayName: 'Display Kernel Tests'


