
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

container: grahamschock/composite_dev_env:latest


steps:
- script: |
    cd src/
    make init
    make
    make run RUNSCRIPT=kernel_tests.sh run
  displayName: 'Trying to build system'
