COMPONENT = test_crt_blkpt_1t.o
INTERFACES=
DEPENDENCIES=
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format $(LIBSLRAW) -lsl_mod_fprr -lsl_thd_static_backend -lsl_blkpt
OBJLIBS += $(POSIX_LIB)
include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
