[system]
description = "Simplest system with capability manager to test initialization order. NOTE: This fails currently as capmgr assumes a scheduler."

[[components]]
name = "booter"
img  = "no_interface.llbooter"
implements = [{interface = "init"}, {interface = "addr"}]
deps = [{srv = "kernel", interface = "init", variant = "kernel"}]
constructor = "kernel"

[[components]]
name = "capmgr"
img  = "capmgr.simple"
deps = [{srv = "booter", interface = "init"}, {srv = "booter", interface = "addr"}]
implements = [{interface = "capmgr"}, {interface = "init"}, {interface = "memmgr"}, {interface = "capmgr_create"}]
constructor = "booter"

[[components]]
name = "ping"
img  = "tests.unit_pingpong"
deps = [{srv = "pong", interface = "pong"}, {srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
baseaddr = "0x1600000"
constructor = "booter"

[[components]]
name = "pong"
img  = "pong.pingpong"
deps = [{srv = "capmgr", interface = "init"}, {srv = "capmgr", interface = "capmgr_create"}]
implements = [{interface = "pong"}]
constructor = "booter"
